name: Deployment Pipeline

on:
  push:
    branches:
      - main

jobs:
  simple_deployment_pipeline:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v6
        with:
          node-version: "24"

      - name: Install Dependencies
        run: npm install

      - name: Check Style
        run: npm run eslint
